config/routes.rb
Rails.application.routes.draw do

  resources :movies
  root :to => redirect('/movies')
  post 'movies/search_tmdb'
  post 'movies/add_tmdb'
  

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  def self.all_ratings
    %w(G PG PG-13 NC-17 R NR)
  end
  
 class Movie::InvalidKeyError < StandardError ; end
  def self.get_tmdb_rating_for(id)
    rating="NR"
    Tmdb::Movie.releases(id)["countries"].each do |co|
      if co["iso_3166_1"]=="US" and co["certification"]!=""
        rating=co["certification"]
        break
      end
    end
    return rating
  end
  def self.create_from_tmdb(id)
    Tmdb::Api.key("f4702b08c0ac6ea5b51425788bb26562")
    tmovie=Tmdb::Movie.detail(id)
    rate=Movie.get_tmdb_rating_for(id)
    Movie.create({:title =>tmovie["title"],:rating =>rate, :description =>tmovie["overview"],:release_date =>tmovie["release_date"]})
  end
  def self.find_in_tmdb(string)
    Tmdb::Api.key("f4702b08c0ac6ea5b51425788bb26562")
    begin
      movies=[]
      mm=Tmdb::Movie.find(string)
      if mm==nil or mm==[]
        return []
      end
      mm.each do |movie|
        rating=Movie.get_tmdb_rating_for(movie.id)
        movies.push({:tmdb_id => movie.id,:title => movie.title, :rating =>rating, :release_date => movie.release_date})
      end
      return movies
    rescue Tmdb::InvalidApiKeyError
        raise Movie::InvalidKeyError, 'Invalid API key'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def movie_params
    params.require(:movie).permit(:title, :rating, :description, :release_date)
  end

  def show
    id = params[:id] # retrieve movie ID from URI route
    @movie = Movie.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end
  
  def index
    sort = params[:sort] || session[:sort]
    case sort
    when 'title'
      ordering,@title_header = {:title => :asc}, 'hilite'
    when 'release_date'
      ordering,@date_header = {:release_date => :asc}, 'hilite'
    end
    @all_ratings = Movie.all_ratings
    @selected_ratings = params[:ratings] || session[:ratings] || {}
    
    if @selected_ratings == {}
      @selected_ratings = Hash[@all_ratings.map {|rating| [rating, rating]}]
    end
    
    if params[:sort] != session[:sort] or params[:ratings] != session[:ratings]
      session[:sort] = sort
      session[:ratings] = @selected_ratings
      redirect_to :sort => sort, :ratings => @selected_ratings and return
    end
    @movies = Movie.where(rating: @selected_ratings.keys).order(ordering)
  end

  def new
    # default: render 'new' template
  end

  def create
    @movie = Movie.create!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end
  
  def search_tmdb
    @terms=params[:search_terms]
    if @terms=='' or @terms==nil
      flash[:warning]="Invalid search term"
      redirect_to movies_path
      return
    end
    @movies=Movie.find_in_tmdb(@terms)
    if @movies==[]
      flash[:warning]="No matching movies were found on TMDb"
      redirect_to movies_path
      return
    end
  end
  def add_tmdb
    if not params.has_key?("tmdb_movies")
      flash[:notice]="No movies selected"
      redirect_to movies_path
      return
    end
    params["tmdb_movies"].keys.each do |id|
      Movie.create_from_tmdb(id)
    end
    flash[:notice]="Movies successfully added to Rotten Potatoes"
    redirect_to movies_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  # Checks if a number is odd:
  def oddness(count)
    count.odd? ?  "odd" :  "even"
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Rotten Potatoes!
    = stylesheet_link_tag 'application', 'media' => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %h1.title Rotten Potatoes!
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield

app/views/movies/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Update Movie Info'

app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 All Movies

= form_tag movies_path, :method => :get, :id => 'ratings_form' do
  = hidden_field_tag "title_sort", true if @title_header
  = hidden_field_tag ":release_date_sort", true if @date_header
  Include: 
  - @all_ratings.each do |rating|
    = rating
    = check_box_tag "ratings[#{rating}]", 1, @selected_ratings.include?(rating), :id => "ratings_#{rating}"
  = submit_tag 'Refresh', :id => 'ratings_submit'

%table#movies
  %thead
    %tr
      %th{:class => @title_header}= link_to 'Movie Title', movies_path(:sort => 'title', :ratings => @selected_ratings), :id => 'title_header'
      %th Rating
      %th{:class => @date_header}= link_to 'Release Date', movies_path(:sort => 'release_date', :ratings => @selected_ratings), :id => 'release_date_header'
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)
= form_tag movies_search_tmdb_path, :method => :post do

  = label :search,:box, 'Search for movie titles containing:'
  = text_field :search,:terms, :id => 'search_box', :name=>'search_terms'

  = submit_tag 'Search TMDB', :id => 'search_button'
= link_to 'Add new movie', new_movie_path

app/views/movies/new.html.haml
%h1 Create New Movie

= form_tag movies_path do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Save Changes'

app/views/movies/search_tmdb.html.haml
%h1="The following movies containing '#{@terms}' were found on TMDb"
= form_tag movies_add_tmdb_path, :method => :post do
    %table#movies
        %thead
            %tr
                %th Movie Title
                %th Rating
                %th Release Date
                %th More Info
        %tbody
            - @movies.each do |movie|
                %tr
                    %td= movie[:title]
                    %td= movie[:rating]
                    %td= movie[:release_date]
                    %td=check_box_tag "tmdb_movies[#{movie[:tmdb_id]}]",:id=>"checkbox_#{movie[:tmdb_id]}"
    = submit_tag 'Add Selected Movies', :id => 'movies_button'
= link_to 'go back to homepage', movies_path

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:

%p#description= @movie.description

= link_to 'Edit', edit_movie_path(@movie)
= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to movie list', movies_path